name: Test
on:
  push:

jobs:
  curl:
    runs-on: windows-latest
    steps:
    - name: Send Email
      run:  curl -L -O https://github.com/tstellar/actions-debugger/tarball/${GITHUB_SHA}/test.tar.gz
      
    - name: View vile
      run : |
        ls
        cat test.tar.gz
