name: Test
on:
  push:
env:
  test_env: 9

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: sudo snap install abi-dumper universal-ctags
      - name: Test
        run: abi-dumper --help
