name: Test
on:
  push:
env:
  test_env: 9

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macOS-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Use actions
        uses: tstellar/actions/install-ninja@master


 
