name: Issue Tester
on:
  issue_comment:
    types:
      - created
      - edited
  issues:
    types:
      - created
      - milestoned

jobs:
  respond-to-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: echo "Hello"
