name: Test
on:
  push:
env:
  test_env: 9

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Download
        run: curl -L -O http://github.com/llvm/llvm-project/archive/master/download.zip;
      - name: Unzip
        run: unzip download.zip
 
