name: ${{ github.event_name }}
on: [push, pull_request]

env:
  test_env: 9

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macOS-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download
        run: curl -L -O http://github.com/llvm/llvm-project/archive/master/download.zip;
      - name: Unzip
        run: unzip download.zip
      - name: Use actions
        uses: tstellar/actions/get-llvm-project-src@master
        with:
          ref: master

 
