name: Commit Emailer
on:
  push:

jobs:
  send-email:
    runs-on: macOS-latest
    steps:
    - name: clang verbose
      run: clang --verbose
    - name: libcxx path
      run: echo "int main(){}" | clang++ -x c++ -### -o test.o -
    - name: Find mutex
      run: find / -iname mutex
      
      
